language: lisp
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-7-dev
      - lib32stdc++-7-dev

env:
  matrix:
    - LISP=abcl
    - LISP=sbcl COVERALLS=true
    - LISP=sbcl32
    - LISP=ccl
    - LISP=ccl32
    - LISP=clisp
    - LISP=clisp32

jobs:
  allow_failures:
    - env: LISP=ccl32

# this bit is just testing that travis correctly sets up ASDF to find
# systems placed somewhere within ~/lisp. You can remove this section
# in your own .travis.yml file.
before_script:
  - echo "(defsystem :dummy-cl-travis-system)" > ~/lisp/dummy-cl-travis-system.asd

install:
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^# cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/sionescu/cl-travis/master/install.sh | sh;
    fi
  - cl -e '(ql:update-all-dists :prompt nil)'
  - git clone https://github.com/fukamachi/cl-coveralls ~/lisp/cl-coveralls

script:
  - ./run-tests.bash


notifications:
  email: false
